'use client'

import { useEffect } from 'react'
import { useRouter } from 'next/navigation'

export default function AdminRedirect() {
  const router = useRouter()

  useEffect(() => {
    // Client-side redirect to the static HTML file generated by TinaCMS
    // This bypasses static hosting rewrite limitations
    window.location.href = '/admin/index.html'
  }, [router])

  return (
    <div className="min-h-screen flex items-center justify-center bg-[var(--color-bg-base)]">
      <div className="text-[var(--color-text-muted)] text-[14px] animate-pulse">
        正在跳转至管理后台...
      </div>
    </div>
  )
}
