/**
 * Auto-generated by scripts/bundle-data.mjs. Do not edit manually.
 */
export const bundleData = {
  "posts": [
    {
      "slug": "技术",
      "title": "可以的",
      "date": "2026-06-18",
      "category": "技术",
      "tags": [],
      "excerpt": "",
      "cover": "",
      "published": true,
      "content": "\n测试\n\n"
    },
    {
      "slug": "采用notion",
      "title": "采用notion",
      "date": "2026-06-15",
      "category": "技术",
      "tags": [],
      "excerpt": "",
      "cover": "",
      "published": true,
      "content": "\n从obsidian转移至notion\n\n"
    },
    {
      "slug": "可以啊",
      "title": "可以啊",
      "date": "2026-06-08",
      "category": "技术",
      "tags": [],
      "excerpt": "",
      "cover": "",
      "published": true,
      "content": "\n我可以\n\n"
    },
    {
      "slug": "生活",
      "title": "你好，世界！",
      "date": "2026-05-11",
      "category": "生活",
      "tags": [],
      "excerpt": "",
      "cover": "",
      "published": true,
      "content": "\n你好，世界！\n\n"
    }
  ],
  "food": [
    {
      "slug": "kaoji",
      "title": "厂堂街烤鸡",
      "date": "2026-06-18",
      "location": "厂堂街烤鸡",
      "address": "海曙区厂堂街79号",
      "lng": 121.54772614835929,
      "lat": 29.878635374795106,
      "cover": "https://images.guanyan.me/20260619230307188.webp",
      "images": [
        "https://images.guanyan.me/20260619230307188.webp"
      ],
      "tags": [],
      "excerpt": "",
      "published": true,
      "content": ""
    }
  ],
  "gallery": [
    {
      "slug": "doujiang",
      "title": "doujiang",
      "date": "2026-06-08",
      "category": "日常",
      "cover": "https://images.guanyan.me/IMG_7764.JPG",
      "images": [
        {
          "src": "https://images.guanyan.me/IMG_7764.JPG",
          "width": 1200,
          "height": 800
        }
      ],
      "excerpt": "",
      "published": true,
      "content": "\n \n\n\n![IMG_7764.JPG](https://images.guanyan.me/IMG_7764.JPG)\n\n"
    },
    {
      "slug": "kafei",
      "title": "kafei",
      "date": "2026-06-02",
      "category": "日常",
      "cover": "https://img.215320.xyz/2026/05/fa7d85a90137299c295a3cdbe9790395.png",
      "images": [
        {
          "src": "https://img.215320.xyz/2026/05/fa7d85a90137299c295a3cdbe9790395.png",
          "width": 1200,
          "height": 800
        }
      ],
      "excerpt": "",
      "published": true,
      "content": "\n \n\n"
    }
  ],
  "says": [
    {
      "slug": "ewJEfE9TxizBxtPTLmtyZJ",
      "date": "2026-07-15T11:19:06Z",
      "content": "身体好，这个世界才是属于你的。\n心态好，不着相，那么快乐才是你的。",
      "image": "https://memos.guanyan.me/file/resources/eQE3AqMYyrxAKA4a6JLofS/IMG_7509.jpeg",
      "images": [
        "https://memos.guanyan.me/file/resources/eQE3AqMYyrxAKA4a6JLofS/IMG_7509.jpeg"
      ]
    }
  ],
  "about": "\n你好，欢迎来到 **轨道之外**，我是 **Can Chou**。\n\n这里记录我的美食探访、生活日常和技术折腾。轨道之外时间，慢慢记录，用心感受。\n\n***\n\n## 联系我\n\n* ✉ Email: [wesyzx@gmail.com](mailto:wesyzx@gmail.com)\n* ◆ GitHub: github.com/wesyzx\n* 𝕏 Twitter: [@wesyzx](https://x.com/wesyzx)\n",
  "updatedAt": "2026-09-14T07:17:04.923Z"
};
