/**
 * This file is auto-generated by scripts/bundle-data.mjs
 * DO NOT EDIT MANUALLY
 */
export const bundleData = {
  "posts": [],
  "food": [
    {
      "slug": "123",
      "title": "123",
      "date": "2026-06-12T15:02:46.343Z",
      "location": "海曙区鼓楼",
      "address": "",
      "lng": 39,
      "lat": 0,
      "cover": "https://images.guanyan.me/IMG_7764.JPG",
      "images": [
        "https://images.guanyan.me/IMG_7764.JPG"
      ],
      "tags": [],
      "excerpt": "好吃",
      "published": true,
      "content": "\n"
    }
  ],
  "gallery": [
    {
      "slug": "mont",
      "title": "mont",
      "date": "2026-06-08T05:02:38.624Z",
      "category": "日常",
      "cover": "https://images.guanyan.me/IMG_7764.JPG",
      "images": [
        "https://images.guanyan.me/IMG_7764.JPG"
      ],
      "excerpt": "",
      "published": true,
      "content": "\n"
    }
  ],
  "says": [],
  "more": [
    {
      "slug": "apps",
      "title": "应用",
      "desc": "常用的软件和工具",
      "icon": "📱",
      "content": "\n这里记录我常用的软件和工具。\n\n## 桌面端\n- macOS\n- VS Code\n- Obsidian\n\n## 移动端\n- WeChat\n- Telegram\n"
    },
    {
      "slug": "friends",
      "title": "友情链接",
      "desc": "经常串门的朋友们",
      "icon": "🤝",
      "content": "\n欢迎交换友链！\n\n- [莫赶](https://bugan.com) - 我的个人博客\n- [Google](https://google.com) - 搜索引擎\n"
    },
    {
      "slug": "goods",
      "title": "好物",
      "desc": "买过觉得不错的东西",
      "icon": "🛍️",
      "content": "\n这里记录我买过并觉得非常不错的东西。\n\n- [ ] 示例项 1\n- [ ] 示例项 2\n"
    },
    {
      "slug": "map",
      "title": "人生地图",
      "desc": "去过的地方，走过的路",
      "icon": "🗺️",
      "content": "\n这里记录我去过的地方。\n\n- 杭州\n- 上海\n- 京都\n- 东京\n"
    },
    {
      "slug": "wishlist",
      "title": "愿望清单",
      "desc": "那些想买或想做的事",
      "icon": "🎁",
      "content": "\n这里记录我的愿望清单。\n\n- [ ] 去冰岛看极光\n- [ ] 拥有一台 Leica 相机\n- [ ] 完成这个博客项目\n"
    }
  ],
  "about": "\n你好，欢迎来到 **莫赶**，我是 **Can Chou**。\n\n这里记录我的美食探访、生活日常和技术折腾。莫赶时间，慢慢记录，用心感受。\n\n***\n\n## 联系我\n\n* ✉ Email: [wesyzx@gmail.com](mailto:wesyzx@gmail.com)\n* ◆ GitHub: github.com/wesyzx\n* 𝕏 Twitter: [@wesyzx](https://x.com/wesyzx)\n",
  "douban": [],
  "updatedAt": "2026-06-14T05:58:24.252Z"
};
