/**
 * Auto-generated by scripts/bundle-data.mjs. Do not edit manually.
 */
export const bundleData = {
  "posts": [],
  "food": [
    {
      "slug": "kaoji",
      "title": "厂堂街烤鸡",
      "date": "2026-06-18",
      "location": "厂堂街烤鸡",
      "address": "海曙区厂堂街79号",
      "lng": 121.54772614835929,
      "lat": 29.878635374795106,
      "cover": "https://images.guanyan.me/20260619230307188.webp",
      "images": [
        "https://images.guanyan.me/20260619230307188.webp"
      ],
      "tags": [],
      "excerpt": "",
      "published": true,
      "content": ""
    }
  ],
  "gallery": [
    {
      "slug": "朗霞豆浆",
      "title": "朗霞豆浆",
      "date": "2026-06-08",
      "category": "小吃",
      "cover": "https://images.guanyan.me/IMG_7764.JPG",
      "images": [
        {
          "src": "https://images.guanyan.me/IMG_7764.JPG",
          "width": 1200,
          "height": 800
        }
      ],
      "excerpt": "",
      "published": true,
      "content": "\n \n\n\n![IMG_7764.JPG](https://images.guanyan.me/IMG_7764.JPG)\n\n"
    }
  ],
  "says": [
    {
      "slug": "SBf5HvfQpJV9Kkef7tnge5",
      "date": "2026-09-18T08:02:22Z",
      "content": "看到的：当一个人的满足感主要来自健康身体状态、稳定关系、阅读、运动、自然、创造、真实体验，而不是来自持续购买刺激时，生活成本就会显著下降。\n人一旦减少高刺激、高面子、高欲望消费，真正高质量的生活其实非常便宜。\n最强的生活结构：稳定住房 + 健康饮食 + 规律运动 + 少量高质量社交 + 阅读/兴趣 + 低频旅行 + 不靠消费证明自己。",
      "images": []
    },
    {
      "slug": "KdLWhzTgZpmsCPLXBMinTG",
      "date": "2026-09-18T06:05:20Z",
      "content": "别太快，太快就失去感觉",
      "images": []
    },
    {
      "slug": "ewJEfE9TxizBxtPTLmtyZJ",
      "date": "2026-07-15T11:19:06Z",
      "content": "身体好，这个世界才是属于你的。\n心态好，不着相，那么快乐才是你的。",
      "image": "/api/memos/file/attachments/eQE3AqMYyrxAKA4a6JLofS/IMG_7509.jpeg",
      "images": [
        "/api/memos/file/attachments/eQE3AqMYyrxAKA4a6JLofS/IMG_7509.jpeg"
      ]
    }
  ],
  "about": "\n你好，欢迎来到 **轨道之外**，我是 **Can Chou**。\n\n这里记录我的美食探访、生活日常和技术折腾。轨道之外时间，慢慢记录，用心感受。\n",
  "updatedAt": "2026-09-18T23:40:04.803Z"
};
